### ISSUE TITLE
プレイヤーが上下左右にいい感じに動けるようにする

### ISSUE THREAD

**Issue by soucy-745** [traP-jp/RogueRategy#11]

**Comment by soucy-745** [comment]
今の状態だと上下のみだが、上下左右動かせるようにする
余力があれば、ただの線形の動きではなく気持ち良い動きを目指す

**Comment by soucy-745** [comment]
Shiftキーを押している間は移動速度が遅くなるなども欲しい
InputSystemを用いる

**Comment by alter334** [comment]
これ移動滑らかにするやつはまた後に別でissue立てる感じにしてこのissue閉じても大丈夫ですか?
